### ISSUE TITLE
Decimal datatype does not contain length and Precision

### ISSUE THREAD

**Issue by wjreindersLogicx** [CrossBreezeNL/PowerDesigner-OData-AddIn#13]
<Property Name="Price" Nullable="false" Type="Edm.Decimal"/> gives empty empty length and precision in the model:

![afbeelding](https://user-images.githubusercontent.com/80835698/201882276-0d52f6c0-8d29-4bbb-b8e8-1d8670352e4f.png)

This gives error while running packages in SSIS at the end:

![afbeelding](https://user-images.githubusercontent.com/80835698/201882465-b6590bf1-2d12-42f8-bf7d-ebcb14c7ce20.png)

**Comment by harmen-xb** [comment]
@wjreindersLogicx

Based on the OData specifications we expected the precision and scale to be specified in the EDMX:
![image](https://user-images.githubusercontent.com/97173058/204024151-1a744b71-12f8-4ed6-90eb-83fc3b382dad.png)
http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part3-csdl/odata-v4.0-errata03-os-part3-csdl-complete.html#_Toc453752531

But in the example with basic authentication you provided the precision and scale is not specified:
![image](https://user-images.githubusercontent.com/97173058/204024070-07aa3cf2-ae79-4dab-9b79-39e23a1b3c57.png)

We can also not find a default value for the precision and scale for EDM, so setting a default value doesn't feel like the right solution.

In your future use case, would the precision and scale be set in the Mendix application?

**Comment by harmen-xb** [comment]
To add to this, one solution would be to set the default to the maximum.

In C# the maximum precision is 29 (https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types)

In SQL the maxmum precision is 38 (https://learn.microsoft.com/en-us/sql/t-sql/data-types/decimal-and-numeric-transact-sql?view=sql-server-ver16)

So there is no logical default precision, and also what should the scale be?

**Comment by wjreindersLogicx** [comment]
Ok clear. Is it possible to fix this in the template/configuration before we start generating SSIS?

**Comment by harmen-xb** [comment]
@wjreindersLogicx Yes, you can set default precision and scale values in ModelAttributeInjections in the CrossGenerate configuration.
