### ISSUE TITLE
Text field generate nvarchart without length

### ISSUE THREAD

**Issue by wjreindersLogicx** [CrossBreezeNL/PowerDesigner-OData-AddIn#17]
Text field generate nvarchart without length so no length and right fulldatatype gets exported to the xmodel. 

![image](https://user-images.githubusercontent.com/80835698/224984422-3436b8fa-9dd3-4ee8-85fe-138f91d52212.png)

**Comment by harmen-xb** [comment]
@wjreindersLogicx Can you check the original $metadata XML whether the field has a length specified?

We take what is given by the metadata, so if it's not there we can't fill it in (same as with numeric/decimal).

**Comment by wjreindersLogicx** [comment]
here a screenshot of the model xml: 

![image](https://user-images.githubusercontent.com/80835698/224987518-f37b2b1b-e2dc-40c0-823c-0e4f9be02866.png)

**Comment by harmen-xb** [comment]
Ok, that looks like a bug :). I will pick it up.

**Comment by harmen-xb** [comment]
This issue is fixed in release v0.5.1 (https://github.com/CrossBreezeNL/PowerDesigner-OData-AddIn/releases/tag/v0.5.1)
