### ISSUE TITLE
Update model from Odata metadata does not work on all models

### ISSUE THREAD

**Issue by willem-xbreeze** [CrossBreezeNL/PowerDesigner-OData-AddIn#3]
After reverse engineering a model from the following URL:
https://api.kosmosvize.com.tr/api/$metadata

If i try to update the model i get an error in the script model:
[OData-AddIn ERROR] Exception was thrown during DoCommand [sMenu='Object'; pObject=PDObject[ClassName='Physical Data Model'; Code='Test'; Name='Test'; ObjectLocation='']; sCommandName='UpdateModelFromOdataMetadata']: Er is een uitzondering opgetreden. (Exception from HRESULT: 0x80020009 (DISP_E_EXCEPTION))

**Comment by harmen-xb** [comment]
@willem-xbreeze This should be solved with the latest release: https://github.com/CrossBreezeNL/PowerDesigner-OData-AddIn/releases/tag/v0.4.0-beta
