### ISSUE TITLE
Create model from OData does not read all tables

### ISSUE THREAD

**Issue by willem-xbreeze** [CrossBreezeNL/PowerDesigner-OData-AddIn#7]
Steps to recreate:
Import from odata
tested with following url: https://api.kosmosvize.com.tr/api/$metadata
Only first 20 tables are read properly, then a table without columns, rest is not in model

![image](https://user-images.githubusercontent.com/62752502/200654092-bdb1261d-60b9-4f9e-9fb1-fe20504493d0.png)

**Comment by harmen-xb** [comment]
@willem-xbreeze This should be solved with the latest release: https://github.com/CrossBreezeNL/PowerDesigner-OData-AddIn/releases/tag/v0.4.0-beta
